FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS wordpress;

CREATE USER 'MYSQL_USERNAME'@'%' IDENTIFIED BY 'MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'MYSQL_USERNAME'@'%' IDENTIFIED BY 'MYSQL_PASSWORD' WITH GRANT OPTION;

FLUSH PRIVILEGES;