FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS wordpress;

CREATE USER 'ncolin'@'%' IDENTIFIED BY 'ncolin123';
GRANT ALL PRIVILEGES ON *.* TO 'ncolin'@'%' IDENTIFIED BY 'ncolin123' WITH GRANT OPTION;

CREATE USER 'wp_user'@'%' IDENTIFIED BY 'wp_pass';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'%' IDENTIFIED BY 'wp_pass' WITH GRANT OPTION;

FLUSH PRIVILEGES;