apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-app
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: ft_mysql
        imagePullPolicy: Never
      ports:
      - containerPort: 3306
        name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-app
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql-app
    tier: mysql