##############
# DEPLOYMENT #
##############

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ft_phpmyadmin_image
        ports:
        - containerPort: 5000
          name: http
        imagePullPolicy: Never
---
###########
# SERVICE #
###########

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    protocol: TCP
  selector:
    app: phpmyadmin