##############
# DEPLOYMENT #
##############

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: ft_phpmyadmin_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
###########
# SERVICE #
###########

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.240
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    name: http
